# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b63ba7651e9f024a5c12b3a844b79260bdb6866a2454633136be64093c7a5ab44a819111cce49fee041717874fd3bcd9febd7f6fb83489de8f97e90789dd7dbe

test:
  secret_key_base: 6b0802a7bf9394ae6c1c57c038b9d52f3f56baaed6bf169a6f8485d62ef5ef680ac59eb7173ddec9aabd625af0aa754874eaa5081941aa180e2defd047271114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
